export const PRODUCTS = [
  {
    slug: "freemix-companion",
    name: "Freemix Companion",
    area: "Mixing",
    tagline: "A reference guide built alongside the Freemix mixing series.",
    price: 5,
    cover: "/products/freemix-companion-cover.png",
    buyUrl: "https://compassadmin.gumroad.com/l/nrvln",
    description: [
      "[Needs copy]",
    ],
  },
  {
    slug: "compass-self-assessment-workbook",
    name: "Compass Self-Assessment Workbook",
    area: "All Areas",
    tagline: "[Needs copy]",
    price: null,
    cover: null,
    buyUrl: null,
    description: ["[Needs copy]"],
  },
  {
    slug: "daw-template-design-guide",
    name: "DAW Template Design Guide",
    area: "DAW Proficiency",
    tagline: "[Needs copy]",
    price: null,
    cover: null,
    buyUrl: null,
    description: ["[Needs copy]"],
  },
  {
    slug: "music-release-playbook",
    name: "Music Release Playbook",
    area: "Release Process",
    tagline: "[Needs copy]",
    price: null,
    cover: null,
    buyUrl: null,
    description: ["[Needs copy]"],
  },
];
